### ISSUE TITLE
error adding the library

### ISSUE THREAD

**Issue by matantsu** [antonkrasov/AndroidSocialNetworks#47]
i have just added the library to the `build.gradle` like this:
```
compile('com.github.androidsocialnetworks:library:0.3.7@aar') {
        transitive = true
 }
```

i have made no changes to the app besides that. when i try to run my app it now says:
```
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/root/Android/Sdk/build-tools/21.1.2/dx --dex --no-optimize --output /home/matan/AndroidStudioProjects/Stars/app/build/intermediates/dex/debug --input-list=/home/matan/AndroidStudioProjects/Stars/app/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
  		at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
  		at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
  		at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by bropane** [comment]
I got the same error too. What is happening is your Android Project is going over the 65536 method limit. There are many ways to go about fixing this but I just ended up using the multidex support in the support library. This will help you fix your problem http://developer.android.com/tools/building/multidex.html. Make sure to update your buildToolsVersion in your build.gradle to 21.1.0 or higher.

**Comment by cartierjf** [comment]
Yes this is not related to the library itself. This issue should be closed.
